name: Publish to JitPack

on:
  push:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: List directory contents
      run: ls -la

    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(grep '^version' build.gradle.kts | awk '{print $3}' | tr -d '"')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Run tests
      run: ./gradlew test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          build/test-results/test/*.xml

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        tag_name: 'v${{ env.VERSION }}'
        release_name: 'Release ${{ env.VERSION }}'
        draft: false
        prerelease: false

    - name: Upload JAR to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/checkmate-core-${{ env.VERSION }}.jar
        asset_name: checkmate-core-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive